// Generated by https://quicktype.io

export interface Sample {
  glossary: Glossary;
}

export interface Glossary {
  title:    string;
  GlossDiv: GlossDiv;
}

export interface GlossDiv {
  title:     string;
  GlossList: GlossList;
}

export interface GlossList {
  GlossEntry: GlossEntry;
}

export interface GlossEntry {
  ID:        string;
  SortAs:    string;
  GlossTerm: string;
  Acronym:   string;
  Abbrev:    string;
  GlossDef:  GlossDef;
  GlossSee:  string;
}

export interface GlossDef {
  para:         string;
  GlossSeeAlso: string[];
}
